[2024-11-25T16:00:03.517+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:00:03.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:00:03.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:00:03.546+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:00:03.556+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 15:00:00+00:00
[2024-11-25T16:00:03.562+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:00:03.562+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T15:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmppcmb5skx']
[2024-11-25T16:00:03.563+0000] {standard_task_runner.py:63} INFO - Started process 306 to run task
[2024-11-25T16:00:03.563+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask load
[2024-11-25T16:00:03.576+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:00:03.600+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [running]> on host 587a89e55935
[2024-11-25T16:00:03.673+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T15:00:00+00:00'
[2024-11-25T16:00:03.674+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:00:03.862+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:00:03.863+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:00:03.863+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:00:03.872+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T15:00:00+00:00, execution_date=20241125T150000, start_date=20241125T160003, end_date=20241125T160003
[2024-11-25T16:00:03.898+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:00:03.911+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:00:03.914+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:25.717+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:25.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:19:25.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:19:25.751+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:25.766+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 15:00:00+00:00
[2024-11-25T16:19:25.776+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:25.777+0000] {standard_task_runner.py:63} INFO - Started process 357 to run task
[2024-11-25T16:19:25.776+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T15:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpfvbrk6nj']
[2024-11-25T16:19:25.778+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load
[2024-11-25T16:19:25.794+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:25.821+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:25.890+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T15:00:00+00:00'
[2024-11-25T16:19:25.891+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:26.034+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:26.035+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:26.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:26.043+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T15:00:00+00:00, execution_date=20241125T150000, start_date=20241125T161925, end_date=20241125T161926
[2024-11-25T16:19:26.071+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:26.084+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:26.087+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:13.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:14.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:30:14.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [queued]>
[2024-11-25T16:30:14.027+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:14.064+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 15:00:00+00:00
[2024-11-25T16:30:14.073+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:14.074+0000] {standard_task_runner.py:63} INFO - Started process 327 to run task
[2024-11-25T16:30:14.073+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T15:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpd7tim6c5']
[2024-11-25T16:30:14.075+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask load
[2024-11-25T16:30:14.090+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:14.120+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T15:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:14.197+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T15:00:00+00:00'
[2024-11-25T16:30:14.198+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:14.458+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:14.458+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:14.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:14.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T15:00:00+00:00, execution_date=20241125T150000, start_date=20241125T163014, end_date=20241125T163014
[2024-11-25T16:30:14.530+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:14.544+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:14.547+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
