[2024-11-25T15:00:04.536+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T15:00:04.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T15:00:04.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T15:00:04.565+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T15:00:04.576+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 14:00:00+00:00
[2024-11-25T15:00:04.584+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1171) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T15:00:04.584+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T14:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpzenuq0c6']
[2024-11-25T15:00:04.585+0000] {standard_task_runner.py:63} INFO - Started process 1173 to run task
[2024-11-25T15:00:04.585+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load
[2024-11-25T15:00:04.600+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T15:00:04.631+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T15:00:04.704+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T14:00:00+00:00'
[2024-11-25T15:00:04.705+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T15:00:04.864+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T15:00:04.864+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T15:00:04.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T15:00:04.873+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T14:00:00+00:00, execution_date=20241125T140000, start_date=20241125T150004, end_date=20241125T150004
[2024-11-25T15:00:04.919+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T15:00:04.932+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T15:00:04.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:24.624+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:24.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T16:19:24.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T16:19:24.659+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:24.678+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 14:00:00+00:00
[2024-11-25T16:19:24.690+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:24.692+0000] {standard_task_runner.py:63} INFO - Started process 353 to run task
[2024-11-25T16:19:24.692+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T14:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmph1jh8h0a']
[2024-11-25T16:19:24.695+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask load
[2024-11-25T16:19:24.727+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:24.762+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:24.859+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T14:00:00+00:00'
[2024-11-25T16:19:24.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:25.133+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:25.134+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:25.135+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:25.146+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T14:00:00+00:00, execution_date=20241125T140000, start_date=20241125T161924, end_date=20241125T161925
[2024-11-25T16:19:25.188+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:25.206+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:25.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:13.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:14.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T16:30:14.032+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [queued]>
[2024-11-25T16:30:14.033+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:14.046+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 14:00:00+00:00
[2024-11-25T16:30:14.054+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=315) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:14.055+0000] {standard_task_runner.py:63} INFO - Started process 324 to run task
[2024-11-25T16:30:14.054+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T14:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp1xqqswp0']
[2024-11-25T16:30:14.057+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load
[2024-11-25T16:30:14.073+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:14.103+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T14:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:14.179+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T14:00:00+00:00'
[2024-11-25T16:30:14.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:14.454+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:14.455+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:14.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:14.464+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T14:00:00+00:00, execution_date=20241125T140000, start_date=20241125T163014, end_date=20241125T163014
[2024-11-25T16:30:14.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:14.524+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:14.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
