[2024-11-25T13:34:39.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:39.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-25T13:34:30.866328+00:00 [queued]>
[2024-11-25T13:34:39.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-25T13:34:30.866328+00:00 [queued]>
[2024-11-25T13:34:39.130+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:39.172+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 13:34:30.866328+00:00
[2024-11-25T13:34:39.191+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=267) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:39.193+0000] {standard_task_runner.py:63} INFO - Started process 291 to run task
[2024-11-25T13:34:39.192+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'manual__2024-11-25T13:34:30.866328+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpbccjfa5m']
[2024-11-25T13:34:39.196+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask load
[2024-11-25T13:34:39.231+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:39.305+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load manual__2024-11-25T13:34:30.866328+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:39.469+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T13:34:30.866328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T13:34:30.866328+00:00'
[2024-11-25T13:34:39.477+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:40.182+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:40.184+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:40.206+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=manual__2024-11-25T13:34:30.866328+00:00, execution_date=20241125T133430, start_date=20241125T133439, end_date=20241125T133440
[2024-11-25T13:34:40.234+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task load (Missing required database environment variables.; 291)
[2024-11-25T13:34:40.308+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:40.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
